version: '3'
services:
  php:
    image: bitnami/php-fpm:7.1
    volumes:
      - .:/app

  phpdx: # will use image created by the local Dockerfile
    build: .
    volumes:
     - .:/app
    tty: true
    ports: ["9001:9001"]

  rabbitmq:
    image: "rabbitmq:3.7.4-management"
    hostname: "rabbitmq"
    expose: ["5672"]
    ports: ["15672:15672"]

  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
     - ./data:/data
    expose: ["6379"]

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    tty: true
    volumes:
      - .:/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
